config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "resources#index"

  resources :users, only: [:show] do
    get "shared", to: "shared_resources#index"
    get "curriculums", to: "users_curriculums#index"
    resources :curriculums, only: [:edit, :update, :destroy]

  end

  resources :resources, only: [:new, :create, :show, :index] do
    resources :feedbacks, only: [:new, :create, :destroy]
    resources :comments, only: [:create]
  end

  resources :curriculums, only: [:new, :create, :index, :show] do
    resources :comments, only: [:create]
    get 'upcoming', to: 'curriculum_upcoming#index'
    get 'progress', to: 'curriculum_progress#index'
  end

  resources :curriculums_resources, only: [:create, :destroy]
  resources :curriculums_users, only: [:create, :destroy]

end

app/models/curriculum.rb
class Curriculum < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_many :curriculums_resources
  has_many :resources, through: :curriculums_resources

  has_many :feedbacks, as: :feedbackable
  has_many :comments, as: :commentable

  belongs_to :creator, class_name: "User"

  has_many  :curriculums_users,
            dependent: :destroy

  has_many  :users, through: :curriculums_users

  validates :title, :subtitle, presence: true, length: { minimum: 4 }

  accepts_nested_attributes_for :curriculums_resources

  def no_feedback?
    feedbacks.empty?
  end

  def creator_name
    creator.username if creator
  end

  # TODO delete
  def user
    creator
  end

end
Curriculum.import force: true

app/controllers/curriculums_controller.rb
class CurriculumsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_by_id, only: [:show, :destroy]

  def new
    @curriculum = Curriculum.new
  end

  def create
    @curriculum = current_user.curriculums.build(curriculum_params)
    @curriculum.save ? successful_create : failed_create
  end

  def show
    cookies.signed[:curriculum_id] = nil
    @resources = @curriculum.resources.sort_by do |resource|
      resource.curriculums_resources
        .where(curriculum_id: @curriculum.id)
        .first
        .order
    end
    @tags = aggregate_tags(@resources)
  end

  def index
    if params[:q].nil?
      @curriculums = Curriculum.paginate(page: params[:page],
                                         per_page: 10).all
    else
      @curriculums = Curriculum.search params[:q]
      @curriculums = @curriculums.records
      @curriculums = @curriculums.paginate(page: params[:page],
                                           per_page: 10)
      if @curriculums.empty?
        @curriculums = @curriculums.paginate(page: params[:page],
                                             per_page: 10)
      end
    end
  end

  def edit
    cookies.signed[:curriculum_id] = nil
    @curriculum = Curriculum.find_by(id: params[:id],
                                    creator_id: current_user.id)
    @resources = @curriculum.resources.paginate(page: params[:page],
                                                per_page: 5)
  end

  def update
    @curriculum = Curriculum.find_by(id: params[:id],
                                     creator_id: current_user.id)
    if @curriculum.update(curriculum_params)
      successful_update
    else
      failed_update
    end
  end

  def destroy
    @curriculum.destroy ? successful_destroy : failed_destroy
  end

  private

  def successful_create
    cookies.signed[:curriculum_id] = @curriculum.id
    redirect_to resources_path
  end

  def failed_create
    flash.now[:danger] = @curriculum.errors.full_messages
    render :new
  end

  def successful_update
    redirect_to request.referrer
  end

  def failed_update
    flash.now[:danger] = @curriculum.errors.full_messages
    render :edit
  end

  def successful_destroy
    flash[:success] = "#{@curriculum.title} destroyed"
    redirect_to user_curriculums_path(current_user.id)
  end

  def failed_destroy
    flash[:danger] = "Something went wrong. We'll get right on it!"
    render :edit
  end

  def find_by_id
    @curriculum = Curriculum.find_by(id: params[:id])
  end

  def curriculum_params
    params.require(:curriculum).permit(:title,
                                       :subtitle,
                                       :description,
                                        curriculums_resources_attributes:
                                        [:id, :order])
  end

  def filter_results(result)
    result = result.where(category_id: params[:category_id].to_i) unless params[:category_id] == ""
    result = result.joins("FULL JOIN resources_tag ON resources_tag.resource_id = resource.id").where(tag_id: params[:tag_id]) if params[:tag_id] & !params[:tag_id] == ""
    result = result.all unless !params[:category_id] == ""
  end

  def aggregate_tags(resources)
    tags = []
    resources.each do |resource|
      resource.tags.each do |tag|
        tags << tag
      end
    end
    tags
  end

end

app/helpers/curriculums_helper.rb
module CurriculumsHelper

  def add_resources_link(curriculum)
    if current_user && current_user.created?(curriculum)
      link_to "Add Resources",
        resources_path(curriculum_id: curriculum.id),
        class: "btn btn-primary"
    end
  end

  def edit_curriculum_link(curriculum)
    if current_user && current_user.created?(curriculum)
      link_to "Edit",
        edit_user_curriculum_path(current_user.id, curriculum.id),
        class: "btn btn-primary pull-right"
    end
  end

  def delete_curriculum_link(curriculum)
    link_to "Delete",
      user_curriculum_path(current_user.id, @curriculum.id),
      class: "btn btn-danger pull-right",
      method: :delete
  end

end

app/views/curriculums/_curriculum.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">

      <div class="col-xs-8">
        <h3><%= link_to(curriculum.title.titleize, curriculum_path(curriculum)) %></h3>
        <p><%= curriculum.subtitle %></p>
        <p><i>by <%= curriculum.creator_name %></i></p>
      </div>

      <div class="col-xs-4">
        <%= edit_curriculum_link(curriculum) %>
        <%= copy_curriculum_link(curriculum.id) %>
      </div>

    </div>
  </div>
</div>

app/views/curriculums/_curriculum_form.html.erb
<%= simple_form_for @curriculum, wrapper: :vertical_form do |f| %>
  <%= f.input :title,
    placeholder: "e.g. Astronomy 101" %>
  <%= f.input :subtitle,
    placeholder: "e.g. Learn the basics of the universe." %>
  <%= f.input :description,
    placeholder: "e.g. Know thyself and you shall know the secrets of all the universe." %>

  <%= f.submit "Next", class: 'btn btn-success <btn-md></btn-md>'%>
<% end %>

app/views/curriculums/_curriculum_form_edit.html.erb
<%= simple_form_for [current_user, @curriculum],
  wrapper: :vertical_form do |f| %>
  <%= f.input :title,
    placeholder: "e.g. Astronomy 101" %>

  <%= f.input :subtitle,
    placeholder: "e.g. Learn the basics of the universe." %>

  <%= f.input :description,
    placeholder: "e.g. Know thyself and awesome knowledge too!" %>

  <%= f.submit class: "btn btn-success" %>

  <%= add_resources_link(@curriculum) %>

  <%= delete_curriculum_link(@curriculum) %>

  <!-- TODO extract css -->
  <div style="padding-top: 20px">
    <%= will_paginate @resources %>

    <% if !@resources.empty? %>
      <%= f.simple_fields_for :curriculums_resources do |cr_fields| %>
        <%= render 'resources/resource', resource: cr_fields.object.resource,
          order_field: (cr_fields.input :order,
                        input_html: { min: 1,
                                      max: @resources.length }) %>
      <% end %>
    <% end %>

    <%= will_paginate @resources %>
  </div>

<% end %>

app/views/curriculums/_curriculum_form_new.html.erb
<%= simple_form_for @curriculum, wrapper: :vertical_form do |f| %>
  <%= f.input :title,
    placeholder: "e.g. Astronomy 101" %>
  <%= f.input :subtitle,
    placeholder: "e.g. Learn the basics of the universe." %>
  <%= f.input :description,
    placeholder: "e.g. Know thyself and you shall know the secrets of all the universe." %>

  <%= f.submit class: "btn btn-success" %>

<% end %>

app/views/curriculums/edit.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <h1>Edit <%= link_to @curriculum.title,
      curriculum_path(@curriculum) %></h1>
  </div>
</div>

<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <%= render 'curriculum_form_edit' %>
  </div>
</div>

app/views/curriculums/index.html.erb
<%= render 'shared/editing_header' %>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">

    <div class="btn-group" role="group">
      <%= link_to 'Resources', resources_path,
        class: 'btn btn-default' %>
      <%= link_to 'Curriculums', curriculums_path,
        class: 'btn btn-default active' %>
      <%= link_to 'Share Resource', new_resource_path,
        class: 'btn btn-default' %>
      <%= link_to 'Create Curriculum', new_curriculum_path,
        class: 'btn btn-default' %>
    </div>

    <hr>

    <% if !@curriculums.empty? %>
      <%= will_paginate @curriculums %>
      <%= render @curriculums %>
      <%= will_paginate @curriculums %>
    <% else %>
      <h3 class="text-muted">Be the first to create a curriculum!</h3>
    <% end %>

  </div>
</div>

app/views/curriculums/new.html.erb
<%= render 'shared/editing_header' %>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">

    <div class="btn-group" role="group">
      <%= link_to 'Resources', resources_path,
        class: 'btn btn-default' %>
      <%= link_to 'Curriculums', curriculums_path,
        class: 'btn btn-default' %>
      <%= link_to 'Share Resource', new_resource_path,
        class: 'btn btn-default' %>
      <%= link_to 'Create Curriculum', new_curriculum_path,
        class: 'btn btn-default active' %>
    </div>

    <hr>


    <% if current_user %>
      <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
          <h1>Create a Curriculum</h1>
          <%= render 'curriculum_form_new' %>
        </div>
      </div>
    <% else %>
      <h3 class="text-muted">Sign up to create a curriculum :D</h3>
    <% end %>
  </div>
</div>

app/views/curriculums/show.html.erb
<%= render 'shared/top_show', show_object: @curriculum,
                              tags: @tags %>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-xs-8">
        <%= @curriculum.description %>
      </div>
    </div>
  </div>
</div>

<ul class="nav nav-tabs tab-box-top">
  <li role="presentation" class="active"><%= link_to "Everything",
    curriculum_path(@curriculum) %></li>
  <% if current_user && current_user.copied_curriculums.include?(@curriculum)%>
    <li role="presentation" ><%= link_to "Upcoming",
      curriculum_upcoming_path(@curriculum) %></li>
    <li role="presentation" ><%= link_to "Progress",
      curriculum_progress_path(@curriculum) %></li>
  <% elsif current_user %>
    <li role="presentation"><%= link_to "Study Curriculum",
      curriculums_users_path(curriculum_id: @curriculum.id,
                             user_id: current_user.id),
                             method: :post %></li>
  <% end %>
</ul>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render @resources %>
  </div>
</div>

<% @curriculum.comments.each do |comment| %>
  <%= render "shared/comment", comment: comment %>
<% end %>

<div class="row">
  <div class="col-xs-12">
    <%= render "shared/comment_form",
      comment_path: url_for([@curriculum, :comments]) %>
  </div>
</div>