config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "resources#index"

  resources :users, only: [:show] do
    get "shared", to: "shared_resources#index"
    get "curriculums", to: "users_curriculums#index"
    resources :curriculums, only: [:edit, :update, :destroy]

  end

  resources :resources, only: [:new, :create, :show, :index] do
    resources :feedbacks, only: [:new, :create, :destroy]
    resources :comments, only: [:create]
  end

  resources :curriculums, only: [:new, :create, :index, :show] do
    resources :comments, only: [:create]
    get 'upcoming', to: 'curriculum_upcoming#index'
    get 'progress', to: 'curriculum_progress#index'
  end

  resources :curriculums_resources, only: [:create, :destroy]
  resources :curriculums_users, only: [:create, :destroy]

end

app/views/shared/_comment.html.erb
<div class="row">

  <div class="col-xs-1">
  </div>

  <div class="col-xs-11">

    <div class="panel panel-default comment">

      <div class="panel-body">

        <div class="row">

          <div class="col-xs-10">
            <p><strong><%= comment.display_author %>:</strong></p>
            <p><%= comment.body %></p>
          </div>

        </div>

      </div>

    </div>

  </div>

</div>

app/views/shared/_comment_form.html.erb
<div>

  <%= form_for Comment.new, url: comment_path do |f| %>

    <div class="row">

      <div class = "col-xs-12" >
        <%= f.text_area :body, class: "form-control", placeholder: "Type a comment in here", rows: 4 %>
        <%= f.submit "Comment", class: "btn btn-primary btn-sm" %>
      </div>

    </div>

  <% end %>

</div>

app/views/shared/_editing_header.html.erb
<% if curriculum = Curriculum.find_by(id: cookies.signed[:curriculum_id]) %>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <h2 class="inline-headers">Adding Resources to <%= curriculum.title %></h2>
      <% if curriculum %>
        <%= link_to "Finish Adding Resources",
          edit_user_curriculum_path(current_user.id,
                                    curriculum.id),
                                    class: 'btn btn-success' %>
                                <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">

       <%= link_to 'OSLP', root_path, class: "navbar-brand" %>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Discover & Share", resources_path %></li>
        <% if current_user %>
          <li><%= link_to "HQ", user_curriculums_path(current_user) %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>

      <%= render 'shared/nav_search_form' %>

    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_nav_search_form.html.erb
<%= form_tag resources_path,
                            class: "navbar-form navbar-left navbar-form-low",
                            style: "margin-left: 25%",
                            method: "get" do %>

  <div class="form-group">
    <%= text_field_tag :q, nil, placeholder: 'Search for',
                        class: "form-control" %>
  </div>

  <div class="form-group">
    <%= select_tag :category_id,
      options_from_collection_for_select(Category.all, "id", "name" ),
      include_blank: "Category",
      class: "form-control" %>
  </div>

  <div class="form-group">
  <%= select_tag :tag_id,
    options_from_collection_for_select(Tag.all, "id", "name" ),
      include_blank: "Tag",
    class: "form-control" %>
  </div>

  <%= submit_tag "Search", class: "btn btn-default" %>
<% end %>

app/views/shared/_top_show.html.erb
<div class="jumbotron">
  <h1><%= show_object.title.titleize %></h1>
  <div class="row">

    <div class="col-xs-8">
      <p><%= show_object.subtitle %></p>
      <% if show_object.has_attribute?(:credits) %>
        <p>Credit: <%= show_object.credits %></p>
        <% show_object.links.each do |link| %>
          <a href="<%= link.url %>"><%= link.url %></a>
        <% end %>
      <% end %>
      <p>submitted by: <%= link_to "#{show_object.user.username}", show_object.user %></p>
    </div>

    <div class="col-xs-4">
      <div>
        <p>Category: <strong><%= show_object.category_name.titleize %></strong></p>
        <p>Tags:
        <!-- TODO render tags -->
          <% tags.each do |tag| %>
            <span id="tag_box">
              <%= tag.name %>
            </span>
          <% end %>
        </p>
        <%= mark_complete_button(show_object) %>
      </div>
    </div>

  </div>
</div>

<div class="row text-center" id="stats-container">

  <div class="col-xs-4">
    <div class="thumbnail">
      <%= image_tag("interface.png", class: "icon") %>
      <p><%= show_object.attribute_average(:rating) %>/10<br>
        Value Score</p>
    </div>
  </div>

  <div class="col-xs-4">
    <div class="thumbnail">
      <%= image_tag("circle.png", class: "icon" ) %>
      <p><%= show_object.attribute_average(:difficulty) %>/10<br>
        Difficulty Score</p>
    </div>
  </div>

  <div class="col-xs-4">
    <div class="thumbnail">
      <%= image_tag("clock.png", class: "icon") %>
      <p><%= display_time(show_object).gsub(/\n/, '<br/>').html_safe %></p>
    </div>
  </div>

</div>