config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "resources#index"

  resources :users, only: [:show] do
    get "shared", to: "shared_resources#index"
    get "curriculums", to: "users_curriculums#index"
    resources :curriculums, only: [:edit, :update, :destroy]

  end

  resources :resources, only: [:new, :create, :show, :index] do
    resources :feedbacks, only: [:new, :create, :destroy]
    resources :comments, only: [:create]
  end

  resources :curriculums, only: [:new, :create, :index, :show] do
    resources :comments, only: [:create]
    get 'upcoming', to: 'curriculum_upcoming#index'
    get 'progress', to: 'curriculum_progress#index'
  end

  resources :curriculums_resources, only: [:create, :destroy]
  resources :curriculums_users, only: [:create, :destroy]

end

app/views/resources/_resource.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">

      <div class="col-xs-8">
        <!-- Denotes that your editing -->
        <% if params[:user_id] && @curriculum %>
          <%= order_field %>
        <% end %>
        <h3><%= link_to resource.title.titleize, resource_path(resource) %></h3>
        <p><%= resource.subtitle %></p>
        <p><i>submitted by: <%= resource.submitter.username %></i></p>
      </div>

      <div class="col-xs-4">
        <!--TODO: tags-->
        <p>Programming, Algorithms</p>
        <div class="row">
          <div class="col-xs-6">
            <p><%= display_time(resource) %></p>
          </div>
          <div class="col-xs-6">
            <p><%= resource.attribute_average(:rating) %>/10<br>
            Score</p>
          </div>
        </div>

        <!-- params[:id] == curriculum id on curriculum edit page -->
        <% if curriculum_id = (cookies.signed[:curriculum_id] || (@curriculum.id if @curriculum && params[:user_id])) %>
          <%= curriculum_resource_toggle_link(curriculum_id, resource.id) %>
        <% elsif @curriculum && current_user %>
          <%= mark_complete_button(resource) %>
        <% end %>

        <%= resource_url(resource) %>
      </div>

    </div>
  </div>
</div>

app/views/resources/_resource_form.html.erb
<%= simple_form_for(@resource, html: { class: 'form-pad-bottom'
                    }, wrapper: :vertical_form) do |f| %>

  <%= f.input :title %>

  <%= f.input :subtitle %>

  <%= f.input :description %>

  <%= render 'links/link_form', f: f %>

  <%= f.input :media_type,
  collection: Resource.media_types.keys.map(&:humanize),
  value_method: :downcase, as: :select %>

  <%= f.input :credits %>

  <%= f.association :category %>

  <!-- TODO: debug - not creating feedback -->
  <%= render 'feedbacks/feedback_form_nested', f: f %>

  <%= f.submit 'Share', class: "btn btn-success" %>

<% end %>

app/views/resources/index.html.erb
<%= render 'shared/editing_header' %>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">

    <div class="btn-group" role="group">
      <%= link_to 'Resources', resources_path,
        class: 'btn btn-default active' %>
      <%= link_to 'Curriculums', curriculums_path,
        class: 'btn btn-default' %>
      <%= link_to 'Share Resource', new_resource_path,
        class: 'btn btn-default' %>
      <%= link_to 'Create Curriculum', new_curriculum_path,
        class: 'btn btn-default' %>
    </div>

    <hr>

    <% if !@resources.empty? %>
      <%= will_paginate @resources %>
      <%= render @resources %>
      <%= will_paginate @resources %>
    <% else %>
      <h3 class="text-muted">Be the first to share a learning resource!</h3>
    <% end %>

  </div>
</div>

app/views/resources/new.html.erb
<%= render 'shared/editing_header' %>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">

    <div class="btn-group" role="group">
      <%= link_to 'Resources', resources_path,
        class: 'btn btn-default' %>
      <%= link_to 'Curriculums', curriculums_path,
        class: 'btn btn-default' %>
      <%= link_to 'Share Resource', new_resource_path,
        class: 'btn btn-default active' %>
      <%= link_to 'Create Curriculum', new_curriculum_path,
        class: 'btn btn-default' %>
    </div>

    <hr>

    <% if current_user %>
      <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
          <h1>Share a Learning Resource</h1>
          <%= render 'resource_form' %>
        </div>
      </div>
    <% else %>
      <h3 class="text-muted">Sign up to share and the learning resources you love :D</h3>
    <% end %>
  </div>
</div>

app/views/resources/show.html.erb
<%= render partial: 'shared/top_show', locals: { show_object: @resource, tags: @tags } %>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-xs-12">
        <%= @resource.description %>
      </div>
    </div>
  </div>
</div>

</div>

<% @resource.comments.order(created_at: :asc).each do |comment| %>
  <%= render partial: "shared/comment", locals: { comment: comment } %>
<% end %>

<div class="row">

  <div class="col-xs-12">
    <%= render partial: "shared/comment_form", locals:
      { comment_path: url_for([@resource, :comments]) } %>
  </div>

</div>

<div class="footer">
  <p>Icons designed by Google from Flaticon</p>
</div>